# Generated by Django 2.0.6 on 2018-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_bot_https_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='handler_conf',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Handler Configure'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ssl_certificate',
            field=models.FileField(blank=True, null=True, upload_to='telegrambot/ssl/', verbose_name='SSL certificate'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=255),
        ),
    ]
